/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TimetableService } from "../timetable.service";
import { TimetableCreateInput } from "./TimetableCreateInput";
import { Timetable } from "./Timetable";
import { TimetableFindManyArgs } from "./TimetableFindManyArgs";
import { TimetableWhereUniqueInput } from "./TimetableWhereUniqueInput";
import { TimetableUpdateInput } from "./TimetableUpdateInput";

export class TimetableControllerBase {
  constructor(protected readonly service: TimetableService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Timetable })
  async createTimetable(
    @common.Body() data: TimetableCreateInput
  ): Promise<Timetable> {
    return await this.service.createTimetable({
      data: data,
      select: {
        classRoom: true,
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Timetable] })
  @ApiNestedQuery(TimetableFindManyArgs)
  async timetables(@common.Req() request: Request): Promise<Timetable[]> {
    const args = plainToClass(TimetableFindManyArgs, request.query);
    return this.service.timetables({
      ...args,
      select: {
        classRoom: true,
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Timetable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async timetable(
    @common.Param() params: TimetableWhereUniqueInput
  ): Promise<Timetable | null> {
    const result = await this.service.timetable({
      where: params,
      select: {
        classRoom: true,
        createdAt: true,
        endTime: true,
        id: true,
        startTime: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Timetable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTimetable(
    @common.Param() params: TimetableWhereUniqueInput,
    @common.Body() data: TimetableUpdateInput
  ): Promise<Timetable | null> {
    try {
      return await this.service.updateTimetable({
        where: params,
        data: data,
        select: {
          classRoom: true,
          createdAt: true,
          endTime: true,
          id: true,
          startTime: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Timetable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTimetable(
    @common.Param() params: TimetableWhereUniqueInput
  ): Promise<Timetable | null> {
    try {
      return await this.service.deleteTimetable({
        where: params,
        select: {
          classRoom: true,
          createdAt: true,
          endTime: true,
          id: true,
          startTime: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
